### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jorgelon** [flowstatedev/gc-private#2]
When I try to use the script with python-3.8.3 embed I get this error

Logging in...
Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1240, in request
  File "http\client.py", line 1286, in _send_request
  File "http\client.py", line 1235, in endheaders
  File "http\client.py", line 1006, in _send_output
  File "http\client.py", line 946, in send
  File "http\client.py", line 1409, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\gcprivate.py", line 246, in <module>
    http_req(URL_GC_LOGIN)
  File ".\gcprivate.py", line 97, in http_req
    response = OPENER.open((request), data=post)
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1393, in https_open
  File "urllib\request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)>

**Comment by flowstatedev** [comment]
Should be fixed with: https://github.com/flowstatedev/gc-private/commit/007d33dc1329c91239d5267854435515b7bc6186

Thanks for the bug report!
